apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  labels:
    app: mongo-express
    {{- include "chatbot-survey.labels" . | nindent 4 }}
spec:
  selector:
    app: mongo-express
  ports:
    - port: {{ .Values.mongoExpress.port }}
      targetPort: {{ .Values.mongoExpress.port }}
