apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatbot-survey-local
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: backend-deployment-patch.yaml
  - path: frontend-deployment-patch.yaml
  - path: frontend-service-patch.yaml
  - path: backend-service-patch.yaml
configMapGenerator:
  - name: backend-config
    literals:
      - APP_ENV=development
      - DATABASE_NAME=persuasive_ai_study
      - ALLOWED_ORIGINS=http://localhost:30080,http://localhost:5173
secretGenerator:
  - name: mongodb-secret
    envs:
      - secrets/mongodb.local.env
  - name: backend-secret
    envs:
      - secrets/backend.local.env
generatorOptions:
  disableNameSuffixHash: false
